python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c 1m1 --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c 1m2 --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c 1m3 --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c 2m1 --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c 2m2h --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c 2m2m --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c 3m1 --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c 3m2 --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c 3m2c --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c 4m1 --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c 4m2 --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c 4m2c --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c baseclampbody --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c baseclampbolt --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c gripper_closed --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c gripper_open --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c helicalgear1 --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c helicalgear2 --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c rackgear --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c spiralgear --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c spurgear --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c t2m1bd --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c t2m1bi --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c t3m1c --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c t4m1e --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c tapa2m1 --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c tapa3m1 --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c tapa4m1 --file-ending png
python utils/FGMaskCreator.py -p /mnt/d/Data/3d-adam-tests/adam3d_unsupervised/ -o ./fg_masks/adam3d_masks/ -c tapatbb --file-ending png